version: '3.8'

services:
  # BEGIN kuma
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    labels:
      # Enable Traefik for this specific "kuma" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.kuma.loadbalancer.server.port=3001
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.kuma-http.entrypoints=http
      - traefik.http.routers.kuma-http.rule=Host(`${kuma_url}`)
      # Use the traefik-network network (declared below)
      - traefik.docker.network=traefik-network
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.kuma-https.entrypoints=https
      - traefik.http.routers.kuma-https.rule=Host(`${kuma_url}`)
      - traefik.http.routers.kuma-https.tls=true
      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.kuma-https.tls.certresolver=le
      # https-redirect middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Plug middleware to redirect HTTP to HTTPS
      - traefik.http.routers.kuma-http.middlewares=https-redirect
      - traefik.http.routers.kuma-https.middlewares=admin-auth
    volumes:
      - ./uptime_kuma_data:/app/data
    env_file:
      - ./.kuma.env
    networks:
      - app-network
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-network
  # END kuma

networks:
  app-network:
    external: true
  traefik-network:
    external: true
