version: '3.8'

services:
  # BEGIN chroma-db
  chroma_db:
    image: chromadb/chroma:latest
    restart: always
    container_name: chroma_db
    volumes:
      - ${chroma_db_path}:/chroma/chroma
    environment:
      CHROMA_SERVER_AUTH_CREDENTIALS: "${chroma_username}:${chroma_password}"
      ANONYMIZED_TELEMETRY: false
    command: "--workers 2 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    networks:
      - app-network
    # END chroma-db

networks:
  app-network:
    external: true
